[Docs,Build] fix build scripts and markdown for building joynr
Change-Id: Ie160eeeb91c45e7cdff82af9049df75a29b79374

diff --git a/docker/joynr-android/scripts/build/java-android-clean-build b/docker/joynr-android/scripts/build/java-android-clean-build
--- a/docker/joynr-android/scripts/build/java-android-clean-build
+++ b/docker/joynr-android/scripts/build/java-android-clean-build
@@ -9,7 +9,21 @@ set -e
 
 ./joynr-setup-android-sdk.sh
 
-mvn clean package -P no-license-and-notice,no-java-formatter,no-checkstyle,android \
+GOAL='install'
+
+while [ "$1" != "" ]; do
+    case $1 in
+        package )               GOAL='package'
+                                ;;
+        install )               GOAL='install'
+                                ;;
+        * )                     echo "invalid argument"
+                                exit 1
+    esac
+    shift
+done
+
+mvn clean $GOAL -P no-license-and-notice,no-java-formatter,no-checkstyle,android \
 -DskipTests=false \
 -Dmaven.test.failure.ignore=true \
 -Denforcer.skip=true -Dmaven.compile.fork=true \
