[Docker] Update Node.js to version 8.16.2
Also add version 12.22.2 to javascript/Dockerfile and
joynr-runtime-environment-base/Dockerfile.

diff --git a/docker/joynr-javascript/scripts/build/javascript-clean-build b/docker/joynr-javascript/scripts/build/javascript-clean-build
--- a/docker/joynr-javascript/scripts/build/javascript-clean-build
+++ b/docker/joynr-javascript/scripts/build/javascript-clean-build
@@ -28,11 +28,24 @@ while [ "$1" != "" ]; do
   shift
 done
 
+log "Print node version"
+if [ -f $NVM_DIR/nvm.sh ]
+then
+    source $NVM_DIR/nvm.sh
+    echo "NVM version:"
+    nvm --version
+    echo "NVM list"
+    nvm list
+fi
+echo "NODE version:"
+node --version
+echo "NPM version:"
+npm --version
+
 (
   log "INSTALL JOYNR BASE MODEL, TOOLS AND INFRASTRUCTURE SERVICES"
   mvn clean install -P no-license-and-notice,no-java-formatter,no-checkstyle -DskipTests
 )
-
 
 if [ "$SKIPTESTS" == "false" ]
 then
@@ -45,31 +58,58 @@ then
     mosquitto -c /data/src/docker/joynr-base/mosquitto.conf &
     MOSQUITTO_PID=$!
 
+    function stopservices
+    {
+        echo '####################################################'
+        echo '# stop services'
+        echo '####################################################'
+
+        stopGcd
+
+        echo "stop mosquitto"
+        kill -TERM $MOSQUITTO_PID
+        wait $MOSQUITTO_PID
+        /data/src/docker/joynr-base/scripts/stop-db.sh
+    }
+
+    set +e # stop services even if there are failing tests or startGcd fails
     startGcd
+    SUCCESS=$?
+    if [ "$SUCCESS" != "0" ];
+    then
+        echo '########################################################'
+        echo '# Start GCD failed with exit code:' $SUCCESS
+        echo '########################################################'
+
+        stopservices
+        exit $SUCCESS
+    fi
 fi
 
 (
-  echo "building joynr JavaScript API"
-  cd javascript
-  mvn clean install \
-  -Dskip.copy-notice-file=true \
-  -Dskip.unpack-license-info=true \
-  -DskipTests=$SKIPTESTS
+    log "building joynr JavaScript API"
+    cd javascript
+    mvn clean install \
+    -Dskip.copy-notice-file=true \
+    -Dskip.unpack-license-info=true \
+    -DskipTests=$SKIPTESTS
+    SUCCESS=$?
 
-  echo "building joynr npm generator"
-  cd ../tools/generator/joynr-generator-npm
-  mvn clean install
+    if [ "$SUCCESS" == "0" ];
+    then
+        log "building joynr npm generator"
+        cd ../tools/generator/joynr-generator-npm
+        mvn clean install
+        SUCCESS=$?
+    fi
+    exit $SUCCESS
 )
+EXIT_CODE=$?
 
+set -e
 if [ "$SKIPTESTS" == "false" ]
 then
-    echo '####################################################'
-    echo '# stop services'
-    echo '####################################################'
-
-    stopGcd
-    kill -TERM $MOSQUITTO_PID
-    wait $MOSQUITTO_PID
-    /data/src/docker/joynr-base/scripts/stop-db.sh
+    stopservices
 fi
 
+exit $EXIT_CODE
